### ISSUE TITLE
rsync?

### ISSUE THREAD

**Issue by pepa65** [matteoserva/MegaFuse#22]
It seems rsync doesn't really work, in that it always transfers the files, also if they are already there. Is this a problem with the Mega API, or in the implementation of MegaFuse?

**Comment by sgregori** [comment]
Rsync needs to be installed at 2 peers, when you mount a drive over SSHFS, CURLFTPFS, or MegaFS, the rsync will not work well because the 2 rsync daemons runs on same host and the archives are remotely and this isnt a good thing.

**Comment by tYYGH** [comment]
Rsync can perfectly be used between two "local" folders. IMHO, this is rather a matter of Mega not storing files' timestamps. Try again with rsync --ignore-times, or rsync --size-only. Either will only work if you're sure that any change to a file will change its size too, though…

**Comment by pepa65** [comment]
Allright, the timestamps! that's a helpful suggestion, to do --ignore-times.

**Comment by pepa65** [comment]
Reporting back: --ignore-times still causes full uploads here, and eventually leads to crashes. Using --size-only works well (apart from the fact that there is no guarantee here about the filesize being different when a file changes...). Both works fine as well. So from my experience here, --ignore-times is NOT recommended.
