### ISSUE TITLE
doesn't work with live/rescue/boot cd

### ISSUE THREAD

**Issue by dj-nitehawk** [matteoserva/MegaFuse#24]
i was trying to backup a cloned copy of my os partition straight on to mega.co.nz by mounting it with megafuse from a boot cd.

i was able to mount the mega file system and copy smaller files but it fails halfway through when trying to copy a 40gb partition. i tried with `dd`, `partclone`, `fsarchiver`.

i think the reason is because megafuse ran out of temporary space on the ramdrive.

does megafuse copy files to a temp disk location before beginning upload to mega?

could this somehow be avoided and upload directly to mega so we can use megafuse from boot cds where temp drive space is low or unavailable?

thanks!

**Comment by seliver** [comment]
It can't be done as you ask. Something similar is answered here: 
https://github.com/matteoserva/MegaFuse/issues/28
