### ISSUE TITLE
Does not compíle on Fedora 21

### ISSUE THREAD

**Issue by ufa** [matteoserva/MegaFuse#25]
Hello,
I am trying to compile on Fedora 21, but I am getting this erros (after fiddling with dependencies, which I think is ok now):

$ make
g++ -I inc -I /usr/include/cryptopp -I sdk -std=c++0x -O0 -g -fstack-protector-all -Wall  -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse  -D_GLIBCXX_DEBUG  -c src/megacli.cpp -o src/megacli.o
src/megacli.cpp: In function ‘void createthumbnail(const char*, unsigned int, std::string*)’:
src/megacli.cpp:104:43: error: ‘JPEG_EXIFROTATE’ was not declared in this scope
   if (!(dib = FreeImage_Load(fif,filename,JPEG_EXIFROTATE | JPEG_FAST | (size << 16)))) return;
                                           ^
src/megacli.cpp:115:53: error: ‘FIF_RAW’ was not declared in this scope
   if (!(dib = FreeImage_Load(fif, filename, (fif == FIF_RAW) ? RAW_PREVIEW : 0))) return;
                                                     ^
src/megacli.cpp:115:64: error: ‘RAW_PREVIEW’ was not declared in this scope
   if (!(dib = FreeImage_Load(fif, filename, (fif == FIF_RAW) ? RAW_PREVIEW : 0))) return;
                                                                ^
src/megacli.cpp:146:50: error: ‘JPEG_BASELINE’ was not declared in this scope
     if (FreeImage_SaveToMemory(FIF_JPEG,dib,hmem,JPEG_BASELINE | JPEG_OPTIMIZE | 85))
                                                  ^
src/megacli.cpp:146:66: error: ‘JPEG_OPTIMIZE’ was not declared in this scope
     if (FreeImage_SaveToMemory(FIF_JPEG,dib,hmem,JPEG_BASELINE | JPEG_OPTIMIZE | 85))
                                                                  ^
src/megacli.cpp: In function ‘void setprompt(prompttype)’:
src/megacli.cpp:852:3: warning: statement has no effect [-Wunused-value]
  rl_callback_handler_install(get_prompt(),process_line);
   ^
src/megacli.cpp: In function ‘void process_line(char*)’:
src/megacli.cpp:1055:23: warning: statement has no effect [-Wunused-value]
    if (words.size()) add_history(line);
                       ^
In file included from /usr/include/cryptopp/modes.h:12:0,
                 from sdk/megacrypto.h:25,
                 from src/megacli.cpp:57:
/usr/include/cryptopp/algparam.h: In instantiation of ‘CryptoPP::ConstByteArrayParameter::ConstByteArrayParameter(const T&, bool) [with T = std::basic_string<char>]’:
/usr/include/cryptopp/filters.h:793:132:   required from here
/usr/include/cryptopp/algparam.h:26:69: warning: unused variable ‘cryptopp_assert_26’ [-Wunused-variable]
         CRYPTOPP_COMPILE_ASSERT(sizeof(CPP_TYPENAME T::value_type) == 1);
                                                                     ^
In file included from /usr/include/cryptopp/modes.h:12:0,
                 from sdk/megacrypto.h:25,
                 from src/megacli.cpp:57:
/usr/include/cryptopp/algparam.h: In instantiation of ‘void CryptoPP::AlgorithmParametersTemplate<T>::MoveInto(void*) const [with T = CryptoPP::RandomNumberGenerator*]’:
src/megacli.cpp:2366:1:   required from here
/usr/include/cryptopp/algparam.h:322:35: warning: unused variable ‘p’ [-Wunused-variable]
   AlgorithmParametersTemplate<T>* p = new(buffer) AlgorithmParametersTemplate<T>(*this);
                                   ^
src/megacli.cpp: At global scope:
src/megacli.cpp:928:6: warning: ‘void process_line(char*)’ defined but not used [-Wunused-function]
 void process_line(char* line)
      ^
src/megacli.cpp:839:20: warning: ‘const char* get_prompt()’ defined but not used [-Wunused-function]
 static const char* get_prompt(void)
                    ^
In file included from /usr/include/cryptopp/secblock.h:7:0,
                 from /usr/include/cryptopp/modes.h:8,
                 from sdk/megacrypto.h:25,
                 from src/megacli.cpp:57:
/usr/include/cryptopp/misc.h:548:20: warning: ‘std::string CryptoPP::StringNarrow(const wchar_t*, bool)’ defined but not used [-Wunused-function]
 static std::string StringNarrow(const wchar_t *str, bool throwOnError = true)
                    ^
Makefile:43: recipe for target 'src/megacli.o' failed
make: *** [src/megacli.o] Error 1

Any help will be appreciated.
ufa

**Comment by matteoserva** [comment]
apparently it's a missing header from libfreeimage. what's the version installed on your system?

**Comment by ufa** [comment]
3.10.0

**Comment by matteoserva** [comment]
with freeimage 3.15 has the missing #defines, are you able to update it?

**Comment by ufa** [comment]
I can do it, but I have 3.10, not 3.15

**Comment by matteoserva** [comment]
please download and install it from the sources at http://freeimage.sourceforge.net/

**Comment by ufa** [comment]
It worked, thanks.

**Comment by zzbulgarinzz** [comment]
`[root@centos6 FreeImage]# make install
make -f Makefile.gnu install 
make[1]: Entering directory `/tmp/FreeImage'
install -d //usr/include //usr/lib
install -m 644 -o root -g root Source/FreeImage.h //usr/include
install -m 644 -o root -g root libfreeimage.a //usr/lib
install -m 755 -o root -g root libfreeimage-3.17.0.so //usr/lib
ln -sf libfreeimage-3.17.0.so //usr/lib/libfreeimage.so.3
ln -sf libfreeimage.so.3 //usr/lib/libfreeimage.so	
make[1]: Leaving directory `/tmp/FreeImage'
`
`[root@centos6 MegaFuse-master]# make
g++ -I inc -I /usr/include/cryptopp -I sdk -std=c++0x -O0 -g -fstack-protector-all -Wall  -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse   -D_GLIBCXX_DEBUG  -c src/MegaFuseApp.cpp -o src/MegaFuseApp.o
In file included from src/MegaFuseApp.cpp:7:
sdk/megacrypto.h:24:22: error: cryptlib.h: Нет такого файла или каталога
sdk/megacrypto.h:25:19: error: modes.h: Нет такого файла или каталога
sdk/megacrypto.h:26:21: error: integer.h: Нет такого файла или каталога
sdk/megacrypto.h:27:17: error: aes.h: Нет такого файла или каталога
sdk/megacrypto.h:28:19: error: osrng.h: Нет такого файла или каталога
sdk/megacrypto.h:29:17: error: sha.h: Нет такого файла или каталога
sdk/megacrypto.h:30:18: error: rsa.h: Нет такого файла или каталога
sdk/megacrypto.h:31:22: error: nbtheory.h: Нет такого файла или каталога
sdk/megacrypto.h:32:22: error: algparam.h: Нет такого файла или каталога
In file included from src/MegaFuseApp.cpp:7:
sdk/megacrypto.h:34: ошибка: ‘CryptoPP’ is not a namespace-name
sdk/megacrypto.h:34: ошибка: expected namespace-name before ‘;’ token
sdk/megacrypto.h:40: ошибка: ‘AutoSeededRandomPool’ does not name a type
sdk/megacrypto.h:42: ошибка: ‘byte’ has not been declared
sdk/megacrypto.h:49: ошибка: ISO C++ запрещает декларации ‘ECB_Mode’ без типа
sdk/megacrypto.h:49: ошибка: expected ‘;’ before ‘<’ token
sdk/megacrypto.h:50: ошибка: ISO C++ запрещает декларации ‘ECB_Mode’ без типа
sdk/megacrypto.h:50: ошибка: expected ‘;’ before ‘<’ token
sdk/megacrypto.h:52: ошибка: ISO C++ запрещает декларации ‘CBC_Mode’ без типа
sdk/megacrypto.h:52: ошибка: expected ‘;’ before ‘<’ token
sdk/megacrypto.h:53: ошибка: ISO C++ запрещает декларации ‘CBC_Mode’ без типа
sdk/megacrypto.h:53: ошибка: expected ‘;’ before ‘<’ token
sdk/megacrypto.h:56: ошибка: ‘byte’ does not name a type
sdk/megacrypto.h:58: ошибка: ‘AES’ has not been declared
sdk/megacrypto.h:59: ошибка: ‘AES’ has not been declared
sdk/megacrypto.h:61: ошибка: ‘byte’ does not name a type
sdk/megacrypto.h:67: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacrypto.h:67: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megacrypto.h:69: ошибка: ‘byte’ has not been declared
sdk/megacrypto.h:69: ошибка: ‘byte’ has not been declared
sdk/megacrypto.h:70: ошибка: ‘byte’ has not been declared
sdk/megacrypto.h:72: ошибка: ‘byte’ has not been declared
sdk/megacrypto.h:73: ошибка: ‘byte’ has not been declared
sdk/megacrypto.h:75: ошибка: ‘byte’ has not been declared
sdk/megacrypto.h:75: ошибка: ‘byte’ has not been declared
sdk/megacrypto.h:77: ошибка: ‘byte’ has not been declared
sdk/megacrypto.h:78: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacrypto.h:78: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megacrypto.h:80: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacrypto.h:80: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megacrypto.h:81: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacrypto.h:81: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megacrypto.h:81: ошибка: ‘static void SymmCipher::xorblock(int)’ cannot be overloaded
sdk/megacrypto.h:80: ошибка: with ‘static void SymmCipher::xorblock(int)’
sdk/megacrypto.h:83: ошибка: ‘byte’ has not been declared
sdk/megacrypto.h:86: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacrypto.h:86: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megacrypto.h:92: ошибка: ‘Integer’ has not been declared
sdk/megacrypto.h:92: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacrypto.h:92: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megacrypto.h:101: ошибка: ‘Integer’ does not name a type
sdk/megacrypto.h:105: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacrypto.h:105: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megacrypto.h:109: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacrypto.h:109: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megacrypto.h:110: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacrypto.h:110: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megacrypto.h:112: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacrypto.h:112: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megacrypto.h:113: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacrypto.h:113: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megacrypto.h:115: ошибка: ‘Integer’ has not been declared
sdk/megacrypto.h:117: ошибка: ‘Integer’ has not been declared
sdk/megacrypto.h:117: ошибка: ‘Integer’ has not been declared
sdk/megacrypto.h:122: ошибка: ‘SHA512’ does not name a type
sdk/megacrypto.h:125: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacrypto.h:125: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
In file included from src/MegaFuseApp.cpp:8:
sdk/megaclient.h:139: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:139: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:329: ошибка: ‘byte’ does not name a type
In file included from src/MegaFuseApp.cpp:8:
sdk/megaclient.h:370: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:370: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:382: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:382: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:382: ошибка: ‘void Command::element(int)’ cannot be overloaded
sdk/megaclient.h:380: ошибка: with ‘void Command::element(int)’
sdk/megaclient.h:414: ошибка: ‘byte’ has not been declared
sdk/megaclient.h:442: ошибка: ‘byte’ does not name a type
sdk/megaclient.h:443: ошибка: ‘byte’ does not name a type
sdk/megaclient.h:446: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:446: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:447: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:447: ошибка: expected ‘;’ before ‘*’ token
sdk/megaclient.h:485: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:485: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:501: ошибка: ‘byte’ does not name a type
sdk/megaclient.h:502: ошибка: ‘byte’ does not name a type
sdk/megaclient.h:504: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:504: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:523: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:523: ошибка: expected ‘;’ before ‘*’ token
sdk/megaclient.h:542: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:542: ошибка: expected ‘;’ before ‘*’ token
sdk/megaclient.h:609: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:609: ошибка: expected ‘;’ before ‘*’ token
sdk/megaclient.h:614: ошибка: ‘byte’ has not been declared
sdk/megaclient.h:800: ошибка: ‘byte’ does not name a type
sdk/megaclient.h:845: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:845: ошибка: expected ‘;’ before ‘*’ token
sdk/megaclient.h:861: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:861: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:941: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:941: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:946: ошибка: ‘byte’ does not name a type
sdk/megaclient.h:951: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:951: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:956: ошибка: ‘byte’ does not name a type
sdk/megaclient.h:962: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:962: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:970: ошибка: ‘byte’ has not been declared
sdk/megaclient.h:980: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:980: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:991: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:991: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:999: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:999: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1015: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1015: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1049: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1049: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1072: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1072: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1281: ошибка: ‘byte’ does not name a type
sdk/megaclient.h:1286: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1286: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1301: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1301: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1441: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1441: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1444: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1444: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1445: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1445: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1446: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1446: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1450: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1450: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1462: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1462: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1496: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1496: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1523: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1523: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1529: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1529: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1773: ошибка: ‘byte’ has not been declared
sdk/megaclient.h:1775: ошибка: ‘byte’ has not been declared
sdk/megaclient.h:1790: ошибка: во врема декларации не допускается инициализировать ‘MegaClient::SIDLEN’ неконстантным выражением
sdk/megaclient.h:1806: ошибка: ‘byte’ has not been declared
sdk/megaclient.h:1817: ошибка: ‘byte’ has not been declared
sdk/megaclient.h:1821: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1821: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1828: ошибка: ‘byte’ has not been declared
sdk/megaclient.h:1853: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1853: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1858: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1858: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1902: ошибка: ‘byte’ has not been declared
sdk/megaclient.h:1931: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1931: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1959: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1959: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megaclient.h:1962: ошибка: ‘byte’ has not been declared
sdk/megaclient.h:1965: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megaclient.h:1965: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
In file included from inc/megafusemodel.h:4,
                 from src/MegaFuseApp.cpp:9:
sdk/megacli.h:62: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacli.h:62: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megacli.h:66: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacli.h:66: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
sdk/megacli.h:94: ошибка: ‘byte’ has not been declared
sdk/megacli.h:114: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
sdk/megacli.h:114: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
In file included from src/MegaFuseApp.cpp:9:
inc/megafusemodel.h:30: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
inc/megafusemodel.h:30: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
src/MegaFuseApp.cpp: In member function ‘virtual void MegaFuseApp::transfer_complete(int, chunkmac_map*, const char*)’:
src/MegaFuseApp.cpp:172: ошибка: нет подходящей функции для вызова ‘MegaClient::topen(handle&, NULL, int&, int&, int)’
sdk/megaclient.h:1493: замечание: претенденты: int MegaClient::topen(const char*, int, int)
sdk/megaclient.h:1496: замечание:              int MegaClient::topen(handle, int)
src/MegaFuseApp.cpp: At global scope:
src/MegaFuseApp.cpp:183: ошибка: ISO C++ запрещает декларации ‘byte’ без типа
src/MegaFuseApp.cpp:183: ошибка: expected ‘,’ or ‘...’ before ‘*’ token
src/MegaFuseApp.cpp: In member function ‘virtual void MegaFuseApp::transfer_complete(int, handle, int)’:
src/MegaFuseApp.cpp:214: ошибка: ‘struct NewNode’ has no member named ‘uploadtoken’
src/MegaFuseApp.cpp:214: ошибка: нет декларации ‘ultoken’ в этой области видимости
src/MegaFuseApp.cpp:214: ошибка: ‘struct NewNode’ has no member named ‘uploadtoken’
src/MegaFuseApp.cpp:217: ошибка: нет декларации ‘filekey’ в этой области видимости
src/MegaFuseApp.cpp:230: ошибка: нет декларации ‘key’ в этой области видимости
src/MegaFuseApp.cpp: In member function ‘virtual void MegaFuseApp::transfer_update(int, m_off_t, m_off_t, dstime)’:
src/MegaFuseApp.cpp:359: ошибка: вызов перегруженной ‘transfer_complete(int&, NULL, NULL)’ имеет неоднозначную трактовку
src/MegaFuseApp.cpp:136: замечание: претенденты: virtual void MegaFuseApp::transfer_complete(int, chunkmac_map*, const char*)
src/MegaFuseApp.cpp:183: замечание:              virtual void MegaFuseApp::transfer_complete(int, handle, int)
src/MegaFuseApp.cpp:360: предупреждение: сравнение знакового и беззнакового целых выражений
src/MegaFuseApp.cpp:362: ошибка: вызов перегруженной ‘transfer_complete(int&, NULL, NULL)’ имеет неоднозначную трактовку
src/MegaFuseApp.cpp:136: замечание: претенденты: virtual void MegaFuseApp::transfer_complete(int, chunkmac_map*, const char*)
src/MegaFuseApp.cpp:183: замечание:              virtual void MegaFuseApp::transfer_complete(int, handle, int)
make: *** [src/MegaFuseApp.o] Ошибка 1
`
I install freeimage but megaclient doesn-t compile. can you help me?
