### ISSUE TITLE
Java method to move file to megafuse mapped folder

### ISSUE THREAD

**Issue by seliver** [matteoserva/MegaFuse#29]
Hi.
I'm working on a little project to move files from one directory to the mega mapped folder.
I tried using File renameTo and Runtime.getRuntime().exec("mv...") but neither of those work. Can this be related to megafuse? Is there a possibility java not being able to move files there?

**Comment by matteoserva** [comment]
1) are you able to move local files to another local directory?
2) can you move a remote file to a local directory?
3) what happens if you first copy then remove the original file?

**Comment by seliver** [comment]
Just picked Files.move(...) and it makes the job.Thanks!
