### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by seliver** [matteoserva/MegaFuse#30]
For some reason i got a segmentation fault running a MegaFuse.
What i was doing is transferring files from a server's folder to a mapped mega folder. I could trasfer about 2GB but then it crashed.

     root@seliver:~/git/dropboxtomega#
     [1]+  Segmentation fault      ./MegaFuse > log.txt  (wd: ~/git/MegaFuse)
     (wd now: ~/git/dropboxtomega)

Unfortunatelly that's the only error message i got. In log.txt there were only the "transferring file" messages. How can i turn on debugging?

**Comment by seliver** [comment]
Can it happen because of no space in disk for megafuse to cache?

**Comment by matteoserva** [comment]
The space might be what's causing the issue. Did you try to send one single big file? In that case I suspect a overflow. 2GB is 2^31 which is the maximum value for a signed int.

**Comment by seliver** [comment]
In my case what I transferred was a bunch of "small" files (0.1MB to 400MB).
Can this happen because of /tmp/mega* fill all the disk space?

On 27/03/2015 02:00, matteo wrote:
>
> The space might be what's causing the issue. Did you try to send one 
> single big file? In that case I suspect a overflow. 2GB is 2^31 which 
> is the maximum value for a signed int.
>
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/matteoserva/MegaFuse/issues/30#issuecomment-86788332>.
>
>
>
>
>
>
>
>
>
>
>
>


-- 
Alexey

**Comment by seliver** [comment]
Can this seg fault be prevented in megafuse?

**Comment by tYYGH** [comment]
FYI, I posted a pull-request regarding the location of the cache. I left the default value to "/tmp" although it should probably be "/var/cache/MegaFuse" or the like.

**Comment by seliver** [comment]
Ok, from the experience I got, the problem was indeed the space.
