### ISSUE TITLE
Warning messages when compiling and finally no mounting

### ISSUE THREAD

**Issue by djuillard** [matteoserva/MegaFuse#31]
I am running a debian 7. I installed the packages as stated in the tuto and then configured the megafuse.conf accordingly.

But when I compile with make ./MegaFuse I got a lot a warnings like : 
"warning: unused variable ‘cryptopp_assert_26’ [-Wunused-variable]"
or
"warning: unused variable ‘p’ [-Wunused-variable]"
or
"warning: ‘std::string CryptoPP::StringNarrow(const wchar_t*, bool)’ defined but not used [-Wunused-function]"

and in the end, it did not mount the drive.

Any chance it already happened to some of you ?

Thanks in advance,

BR

Damien

**Comment by matteoserva** [comment]
The warnings can be safely ignored. They're caused by the MEGA sdk. Once you compiled the code, you have to run it. what happens if you execute ./MegaFuse?

**Comment by djuillard** [comment]
Very sorry for bothering you with such a stupid request from me !!! You are
right, I just forfot to run it after compiling.... and it works very fine
: excellent work, it works great and it is fast ;-). Very sorry again, that
was so obvious but I have not used make commande lines for a longtime...
and we forgot the fundamentals !

Thanks again. I will remove the issue from github.
