### ISSUE TITLE
Reconnect mode, File Cache Size and Disable File Caching

### ISSUE THREAD

**Issue by wiserweb** [matteoserva/MegaFuse#5]
According to http://shfs.sourceforge.net/install.html

SHFS supports reconnect mode. Has this been tested with MegaFuse? Could this be workable method to ensure that endpoints are reconnected even when network conditions are unreliable?

To make mount survive temporary connection outage (reconnect mode):
shfsmount --persistent user@host /mnt/shfs

Additionally, could there be an ability to specify the cache size? It's not clear how the caching of MegaFuse and SHFS work together.

Longer transfers? Increase cache size (1MB cache per file):
shfsmount user@host /mnt/shfs -o cachesize=256

Finally, could there be the ability to disable caching when copying files to mount point when the file system doesn't have enough disk space. For example, copying a 15GB file to /megafs mount point would fail if only 10GB of space is remaining on the local disk. To avoid this condition MegaFuse could be started with -o cachesize=0  or similar operator to temporarily disable caching to enable large files to be copied or moved to /megafs mount point even if disk space is limited.

**Comment by omgbox** [comment]
>  I'll add a cache pruning system that deletes the cache

tottaly in need of this, remote HD 100gb, local disk 25gb, cant do much need to remove cache so often
