### ISSUE TITLE
make error (debian jessie)

### ISSUE THREAD

**Issue by poosey** [matteoserva/MegaFuse#55]
Been trying to compile this thing for a week now with no avail. Everything needed is installed already. Always fails on the misc.h crypto++ part. Here's my log file of the error in question:

make: pkg-config: Command not found
g++ -I inc -I /usr/include/cryptopp -I sdk -std=c++0x -O0 -g -fstack-protector-all -Wall   -D_GLIBCXX_DEBUG  -c src/MegaFuseApp.cpp -o src/MegaFuseApp.o
In file included from /usr/include/fuse/fuse.h:26:0,
                 from /usr/include/fuse.h:9,
                 from inc/megafusemodel.h:7,
                 from src/MegaFuseApp.cpp:9:
/usr/include/fuse/fuse_common.h:33:2: error: #error Please add -D_FILE_OFFSET_BITS=64 to your compile flags!
 #error Please add -D_FILE_OFFSET_BITS=64 to your compile flags!
  ^
src/MegaFuseApp.cpp: In member function â€˜virtual void MegaFuseApp::transfer_update(int, m_off_t, m_off_t, dstime)â€™:
src/MegaFuseApp.cpp:360:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  } else if(endChunk > startChunk && endChunk < it->second.availableChunks.size() && it->second.availableChunks[endChunk]) {
                                              ^
In file included from /usr/include/cryptopp/secblock.h:7:0,
                 from /usr/include/cryptopp/modes.h:8,
                 from sdk/megacrypto.h:25,
                 from src/MegaFuseApp.cpp:7:
/usr/include/cryptopp/algparam.h: In instantiation of â€˜CryptoPP::ConstByteArrayParameter::ConstByteArrayParameter(const T&, bool) [with T = std::basic_string<char>]â€™:
/usr/include/cryptopp/filters.h:793:132:   required from here
/usr/include/cryptopp/misc.h:59:118: warning: unused variable â€˜cryptopp_assert_26â€™ [-Wunused-variable]
 #define CRYPTOPP_COMPILE_ASSERT_INSTANCE(assertion, instance) static CompileAssert<(assertion)> CRYPTOPP_ASSERT_JOIN(cryptopp_assert_, instance)
                                                                                                                      ^
/usr/include/cryptopp/misc.h:62:39: note: in definition of macro â€˜CRYPTOPP_DO_ASSERT_JOINâ€™
 #define CRYPTOPP_DO_ASSERT_JOIN(X, Y) X##Y
                                       ^
/usr/include/cryptopp/misc.h:59:97: note: in expansion of macro â€˜CRYPTOPP_ASSERT_JOINâ€™
 #define CRYPTOPP_COMPILE_ASSERT_INSTANCE(assertion, instance) static CompileAssert<(assertion)> CRYPTOPP_ASSERT_JOIN(cryptopp_assert_, instance)
                                                                                                 ^
/usr/include/cryptopp/misc.h:55:44: note: in expansion of macro â€˜CRYPTOPP_COMPILE_ASSERT_INSTANCEâ€™
 #define CRYPTOPP_COMPILE_ASSERT(assertion) CRYPTOPP_COMPILE_ASSERT_INSTANCE(assertion, __LINE__)
                                            ^
/usr/include/cryptopp/algparam.h:26:9: note: in expansion of macro â€˜CRYPTOPP_COMPILE_ASSERTâ€™
         CRYPTOPP_COMPILE_ASSERT(sizeof(CPP_TYPENAME T::value_type) == 1);
         ^
In file included from /usr/include/cryptopp/modes.h:12:0,
                 from sdk/megacrypto.h:25,
                 from src/MegaFuseApp.cpp:7:
/usr/include/cryptopp/algparam.h: In instantiation of â€˜void CryptoPP::AlgorithmParametersTemplate<T>::MoveInto(void*) const [with T = CryptoPP::RandomNumberGenerator*]â€™:
src/MegaFuseApp.cpp:377:1:   required from here
/usr/include/cryptopp/algparam.h:322:35: warning: unused variable â€˜pâ€™ [-Wunused-variable]
   AlgorithmParametersTemplate<T>* p = new(buffer) AlgorithmParametersTemplate<T>(*this);
                                   ^
In file included from /usr/include/cryptopp/secblock.h:7:0,
                 from /usr/include/cryptopp/modes.h:8,
                 from sdk/megacrypto.h:25,
                 from src/MegaFuseApp.cpp:7:
/usr/include/cryptopp/misc.h: At global scope:
/usr/include/cryptopp/misc.h:549:20: warning: â€˜std::string CryptoPP::StringNarrow(const wchar_t*, bool)â€™ defined but not used [-Wunused-function]
 static std::string StringNarrow(const wchar_t *str, bool throwOnError = true)
                    ^
Makefile:43: recipe for target 'src/MegaFuseApp.o' failed
make: *** [src/MegaFuseApp.o] Error 1

**Comment by matteoserva** [comment]
The first line days that pkg-config is missing. Try installing it and see if it solves the issue

**Comment by poosey** [comment]
Thanks please close this

**Comment by poosey** [comment]
That did the trick, duh
