### ISSUE TITLE
Doubt: What is the function of the "appkey" variable?

### ISSUE THREAD

**Issue by chmercesmoreira** [matteoserva/MegaFuse#69]
Hello, I don't know where to ask this question, that is the reason why I'm creating an issue here, sorry if I did the wrong procedure.

What is the function of the "appkey" variable on the "megafuse.conf" file? Can I use my remote file system without this variable setted?

**Comment by matteoserva** [comment]
this is used to identify the app. If something goes wrong, MEGA has the ability to ban that specific appkey.  you don't have to change it if you don't want to
