### ISSUE TITLE
Error while reading files

### ISSUE THREAD

**Issue by ghost** [matteoserva/MegaFuse#71]
These are the error messages I'm getting while reading files:

This message appears when I try to read big files:
```
topen riuscito
terminate called after throwing an instance of 'std::length_error'
  what():  vector<bool>::_M_fill_insert
```

This other appears when I read a folder containing a lot of files:
```
/usr/include/c++/6.3.1/debug/vector:415:
Error: attempt to subscript container with out-of-bounds index 0, but 
container only holds 0 elements.

Objects involved in the operation:
    sequence "this" @ 0x0x7f4748000d00 {
      type = std::__debug::vector<bool, std::allocator<bool> >;
    }
```
I want to help to solve these problems, if you need any other log file you can ask me and I will try to provide them as soon as possible.

**Comment by DoctorSubtilis** [comment]
I have today the same problem
